version: '3.4'

services:
  platominifastapiservice:
    image: plato:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9003:9000
    privileged: true
    # volumes:
      # - $PWD:/paddle
      # - $PWD.paddlenlp:/home/jovyan/.paddlenlp
